config/routes.rb
Rails.application.routes.draw do
  resources :creatures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
    
    def index 
        @creatures = Creature.all
    end

    def show 
        @creature = Creature.find(params[:id])
    end

   

    def edit
        @creature = Creature.find(params[:id])
    end

    def new
        @creature = Creature.new
    end

    def create
        @creature = Creature.new(creature_params)

        if @creature.save   
            # redirect_to @creature
        else
            render 'new'
        end
    end

    def update
        @creature = Creature.find(params[:id])
        if @creature.update(creature_params)
            redirect_to @creature 
        else
            render 'edit'
        end

    end

    def destroy
        @creature = Creature.find(params[:id])
        @creature.destroy
        redirect_to creatures_path
    end

    private 
    def creature_params
        params.require(:creature).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
        base_title = "Boggable"
        if page_title.empty?
          base_title
        else
          page_title + " | " + base_title
        end
      end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/_form.html.erb
<%= form_with(model: [@creature], local:true) do |form| %>
<p>
<%=  form.label :name %>
<%=  form.text_field :name%>
</p>
<p>
<%=  form.label :description %>
<%=  form.text_field :description %>
</p>
<p>
<%= form.submit %>

<% end %>

app/views/creatures/edit.html.haml
-#<h3><%= render 'form' %></h3>
-#<h3><%= link_to 'Back', creatures_path %><h3>


- provide(:title, "editPage")
%h3= render 'form' 
%h3= link_to 'Back', creatures_path 

app/views/creatures/index.html.haml
%button.add-new= link_to 'Add New Creature', new_creature_path 

- @creatures.each do |creature| 
    %h2= link_to creature.name, creature_path(creature) 
    %p#description= creature.description
    
    %button= link_to 'show', creature_path(creature) 
    %button= link_to 'edit', edit_creature_path(creature) 
    %button= link_to 'destroy', creature_path(creature),
        method: :delete,
        data: {confirm: 'are you sure?' } 
    %hr
    

app/views/creatures/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.haml
-#<%= @creature.name %>
-#<%= @creature.description %>

-#<%= link_to 'Back', creatures_path %>
-#<%= link_to 'Edit', edit_creature_path %>

- provide(:title, "showPage") 

%h1= @creature.name 
%h3= @creature.description 

%p= link_to 'Back', creatures_path 
%p= link_to 'Edit', edit_creature_path 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>